package com.transferrate.app.ui

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.luminance

/**
 * Provider brand-colour mapping used to tint the BEST card so the
 * winning provider's identity reads at a glance.
 *
 * **Generated by `tools/extract_brand_colors.py`** from the bundled
 * `res/drawable-nodpi/logo_<provider>.png` PNGs (which were derived
 * from each provider's official favicon at bundle time, so they ARE
 * the canonical brand colours — no hand-picking, no guessing).  The
 * extractor:
 *
 *   1. drops transparent / near-white / near-black / near-grey pixels,
 *   2. k-means clusters the remaining RGB pixels into 4 groups,
 *   3. picks the most-saturated of the top-2 by population,
 *   4. blends 22% into white for the light-mode tint, 45% into
 *      `#1F2F41` (the dark surface) for the dark-mode tint.
 *
 * The blends keep `MaterialTheme.colorScheme.onSurface` text APCA
 * Body-legible on top — verified by `tools/validate_color_palette.py`.
 *
 * Trademark posture: provider names and logos are trademarks of
 * their respective owners.  This map is used here for nominative
 * identification in a comparison context, not branding or
 * endorsement.  Re-run the extractor whenever a provider logo PNG
 * is updated to keep the tints in sync with the brand.
 */
@Composable
internal fun bestCardTintFor(providerId: String): Color {
    val isDark = MaterialTheme.colorScheme.background.luminance() < 0.5f
    return when (providerId.lowercase()) {
        "ahalia"               -> if (isDark) Color(0xFF12345D) else Color(0xFFAEC0D6)  // brand #023B7F
        "al_ansari"            -> if (isDark) Color(0xFF182E53) else Color(0xFFB3BBCF)  // brand #112C69
        "al_dahab"             -> if (isDark) Color(0xFF126239) else Color(0xFFAEE1BC)  // brand #02A12F
        "aspora"               -> if (isDark) Color(0xFF372A74) else Color(0xFFC9B9E6)  // brand #5523B2
        "federal_exchange"     -> if (isDark) Color(0xFF7B5D3A) else Color(0xFFF9DDBD)  // brand #EC9532
        "gcc_exchange"         -> if (isDark) Color(0xFF186646) else Color(0xFFB2E3C6)  // brand #0FA94D
        "index_exchange"       -> if (isDark) Color(0xFF837C35) else Color(0xFFFEF3B9)  // brand #FDDA26
        "lari"                 -> if (isDark) Color(0xFF7F5A38) else Color(0xFFFCDBBB)  // brand #F58E2C
        "orient_exchange"      -> if (isDark) Color(0xFF776338) else Color(0xFFF6E1BC)  // brand #E2A22E
        "lulu"                 -> if (isDark) Color(0xFF1A678C) else Color(0xFFB4E4F7)  // brand #15ABE7
        "remitly"              -> if (isDark) Color(0xFF213449) else Color(0xFFB9C0C8)  // brand #243954
        "sharaf"               -> if (isDark) Color(0xFF84542B) else Color(0xFFFFD7B3)  // brand #FF8110
        "transfergo"           -> if (isDark) Color(0xFF847724) else Color(0xFFFFF0AD)  // brand #FFD000
        "wise"                 -> if (isDark) Color(0xFF153124) else Color(0xFFB0BEAE)  // brand #083500
        // Fallback: prior dual-tone indigo (used when a provider is
        // newly registered without a bundled logo PNG).
        else                  -> if (isDark) Color(0xFF241776) else Color(0xFFA3ACFF)
    }
}
